// 1 : girl
// 2 : man
// 20 : man small
// 99 : bulle fadeout

export const data = [
{player:1,text:"Tu n’applaudis pas?"},
{player:20,text:"Non."},
{player:99,text:"..."},
{player:2,text:"J’ai une crampe au bras."},
{player:1,text:"	Tu as une crampe simultanée aux deux bras?"},
{player:99,text:"..."},
{player:20,text:"Oui"},
{player:1,text:"	Tu veux que j’appelle le 15?"},
{player:2,text:"Et j’ai une crampe à l’empathie aussi."},
{player:2,text:"Tout mon être a une crampe géante à cause de ce que je viens de voir et d’entendre."},
{player:1,text:"	rohh t’abuses"},
{player:2,text:"Donc dans cette situation il m’est impossible d’applaudir."},
{player:2,text:"Ni de me lever d’ailleurs comme tu peux le constater"},
{player:2,text:"Ni rien. Je dois attendre que ça passe."},
{player:1,text:"	pff je te jure"},
{player:1,text:"	nan mais quoi ça te ferait mal d’applaudir un peu par politesse?"},
{player:1,text:"	sérieusement tu me fais honte"},
{player:99,text:"..."},
{player:2,text:"C’est pas que ça me ferait mal"},
{player:2,text:"C’est par respect pour toutes les autres personnes que j’ai applaudi dans ma vie"},
{player:2,text:"Si elles me voyaient applaudir là maintenant"},
{player:2,text:"Elles auraient de sérieux doutes sur mon goût"},
{player:2,text:"Ce qui remettrait en question et dévaluerait mes applaudissements adressés à elles, dans le passé"},
{player:2,text:"Imagine"},
{player:2,text:"tu es pianiste virtuose"},
{player:2,text:"ton interprétation est reconnue dans le monde pour sa justesse et son absence de sentimentalité. "},
{player:2,text:"on t'applaudit. "},
{player:2,text:"Aux saluts tu vois du coin de l'oeil une personne qui t'applaudit avec une chaleur toute particulière."},
{player:2,text:"tu décides de suivre cette personne pour voir qui d'autre elle applaudit dans sa vie"},
{player:2,text:"et là c'est une catastrophe "},
{player:2,text:"tu vois cette personne applaudir tout et n'importe quoi :"},
{player:2,text:"une émission à la télé, un plat de cuisine soi-disant fait maison, etc."},
{player:2,text:"autant dire que la confiance est brisée."},
{player:99,text:"(…)"},
{player:1,text:"	moi je pense que même si on a pas super aimé il faut quand même applaudir"},
{player:1,text:"	ne serait-ce que pour saluer le courage que ça demande de monter sur scène"},
{player:1,text:"	ou pour rendre hommage aux sacrifices consentis par les musiciens pour leur art "},
{player:1,text:"	toi quand tu étais ado, en rentrant des cours tu jouais à la game cube avec moi"},
{player:1,text:"	alors que ces pianistes, quand iels étaient ados, en plus de leurs études, iels se tapaient 8 heures d'entraînement par jour"},
{player:2,text:"Ma crampe est passée, on se retrouve devant le théâtre."},
{player:99,text:"(Il part)"},
{player:1,text:"	grmbl"},
{player:1,text:"	quel taré"},
{player:1,text:"	le seul point sur lequel il a raison, c’est que tout le monde applaudit pour des raisons différentes"},
{player:99,text:"	(…)"},
{player:1,text:"	je devrais éclaircir mes motifs."},
{player:1,text:"	(mains en haut-parleur)"},
{player:1,text:"	MERCI POUR VOTRE TRAVAIL!"},
{player:1,text:"	C’EST BEAU DE PRENDRE DES RISQUES"},
{player:99,text:"	(…)"},
{player:1,text:"	TOUT TRAVAIL MERITE SALAIRE!"},
{player:1,text:"	SOUTIEN AUX ANNEXES 8 ET 10 DE L’ASSURANCE CHOMAGE!"},
{player:99,text:"	(…)"},
{player:1,text:"	MERCI AUSSI AUX PERSONNES QUI ONT CONSTRUIT LE BATIMENT"},
{player:99,text:"	(…)"},
{player:1,text:"	PARDON POUR MON AMI"},
{player:1,text:"	IL EST UN PEU DÉSAGRÉABLE MAIS IL A BON FOND"},
{player:1,text:"	VOILA BONNE SOIREE"},
{player:1,text:"* sur une idée originale de stéphanie & jérome."}
]