export const data = ["C\'était bien le concert ce soir.",
"superbe même.",
"J\'adore les compositeurs romantiques.",
"ceci dit en y réfléchissant c\'est un peu ironique",
"qu\'à priori la plupart des personnes qui étaient présentes au concert ce soir",
"soient venues (comme moi)",
"avec leurs véhicules thermiques qui crachent du C02 par kilos ",
"participant chacun.e généreusement à la 6e extinction de masse en cours ",
"pour venir écouter une musique exaltant la beauté de la nature.",
"",
"enfin...", 
"pour ce qui me concerne c\'est encore pire",
"parce que je suis tout seul dans ma voiture",
"j\'imagine qu\'il y a des personnes qui étaient *au moins deux* dans leur véhicule",
"",
"ça se trouve il y a même des gens qui sont venus en vélo",
"... ou a pied?",
"il y a peut être des gens de l\'avant-pays qui se sont levé à 5h du matin",
"et qui sont passés par le col de l\'épine pour venir voir le concert.",
"comme on faisait dans le temps pour aller à la ville.",
"ils sont arrivés tout suants et se sont fait juger par leurs voisins qui avaient la clim à fond dans leur auto.",
"...",
"c\'étaient quand même des sacrés hypocrites ces romantiques en fin de compte.",
"si ils étaient vivants à notre époque c\'est sûr qu\'ils feraient 20 vols transatlantique par an",
"pour aller exalter la beauté de la nature",
"à 1 tonne de CO2eq par aller/retour à New York ou Montréal.",
"",
"purée je viens de me faire flasher ou quoi?",
"ah merde je roule à 75 km/h au lieu de 70 km/h.",
"pff",
"la prochaine fois je viens en trottinette électrique."]