export const data = [
"", // apparition de l'ouvreur
"", // apparation de sam 0
"", // l'ouvreur tend la main
"", // sam se met devant l'ouvreur
"", // sam va s'asseoir et l'ouvreur rentre sa main. 
"le programme de ce soir est dédié à l'absence de courage en musique.",
"quels sont les compositeurs et les compositrices,",
"qui au cours de leur carrière",
"on le plus fait preuve d'obséquiosité",
"de lâcheté, de conformisme",
"et se sont compromis avec les pouvoirs en place",
"pour l'avancement de leur carrière",
"au détriment du bon goût",
"de la justice sociale" ,
"ou de la créativité musicale.",
"...",
"quels sont les compositeurs et les compositrices,",
"qui ont pourri l'ambiance sans ménagement",
"ont vilifié leurs confrères et consoeurs",
"n'ont fait preuve d'aucune retenue dans leur désir de séduire les forts",
"et de fouler au pied les faibles,",
"ignorant celles et ceux qui n'avaient besoin que d'un petit encouragement pour que leur talent s'exprime aussi",
"mais au contraire, les assassinant froidement dans le dos avec une petite phrase de mépris.",
"comme par exemple, ils sont à un diner mondain",
"et là personne ne leur demande leur avis à propos de rien",
"mais ils entendent une personne même pas si importante, vétue néanmoins d'un smoking",
"qui dit un truc du genre : ahh oui j'ai entendu untel qui a donné un récital, c'était super",
"et là ils traversent la salle en courant avec leur petit four dans la main,",
"pour lâcher avec un petit rictus :",
"untel? peuh, ça m'a beaucoup déçu, je m'attendais à mieux",
"comme si on en avait quelque chose à faire que ça l'ait personnellement déçu.",
"quels sont les compositeurs et les compositrices,",
"qui ont publiquement mystifié l'exercice de leur art",
"a des fins mesquines",
"pour dissimuler le caractère arbitraire de leur réussite",
"pour masquer tout ce qui aurait trait à de la reproduction sociale ou à du népotisme,",
"pour offusquer leur tours de main, leur méthodes, leur 'astuces' expressives",
"même jusqu'à la conduite très concrète de leur journée de travail,",
"tant leur paranoïa d'arriviste ne leur permet pas de vivre à visage découvert",
"vous voyez ce que je veux dire?",
"vous leur demandez simplement :",
"ah tiens bonjour M. Strauss, comment ça va? comment vous faites pour composer votre musique?",
"et là tout paniqué il répond un truc du genre",
"comment ça? ah ben c'est très simple, j'ai une technique imparable qui consiste à aller me ballader dans la forêt dès l'aube et hop!",
"ou alors, une autre fois :",
"ah tiens bonjour M. Rossini, tiens vous avez l'air fatigué, pas trop dur le travail?",
"et là il répond un truc du genre :",
"ha ha! nan mais moi je travaille jamais, j'ai écrit mon dernier opéra aux toilettes.",
"...",
"vous allez découvrir une programmation spéciale",
"effectuée par un comité d'artistes interprètes irrités",
"qui ont décidé de vous faire écouter, ce qui, selon eux",
"relève de la lâcheté intellectuelle et de l'inculture politique en musique",
"en dernière partie de soirée,",
"notre invité exceptionnel, le baryton Sébastien Soules",
"converti livreur à vélo par nécessité pendant le confinement lié à la maladie de covid-19",
"viendra présenter sa nouvelle pièce d'opéra",
"intitulée:",
"aller chercher soi-même sa pizza en vélo quand on est valide et en bonne santé",
"est une question de dignité humaine.",
"cette soirée est rendue possible par nos généreux mécènes",
"que nous tenons à remercier chaleureusement",
"merci à Uber, Amazon, BNP Paribas et Uniqlo."
]

// "Mardi 25 Avril 2023",
// "20h30",
// "La brèche festival, Chambéry",
// "Durée : 2 heures environ",
// "COURAGE",
// "",
// "photos et enregistrements vidéo ne sont pas autorisés pendant le concert.",
// "",
// "NOTE D'INTENTION",
// "le programme de ce soir est dédié à l'absence de courage en musique.",
// "quels sont les compositeurs et les compositrices,",
// "qui au cours de leur carrière",
// "on le plus fait preuve d'obséquiosité",
// "de lâcheté, de conformisme",
// "et se sont compromis avec les pouvoirs en place",
// "pour l'avancement de leur carrière",
// "au détriment du bon goût",
// "de la justice sociale",
// "ou de la créativité musicale.",
// "",
// "ce soir",
// "vous allez découvrir une programmation spéciale",
// "effectuée par un comité d'artistes interprètes irrités",
// "qui ont décidé de vous faire écouter, ce qui, selon eux",
// "relève de la lâcheté intellectuelle et de l'inculture politique en musique",
// "en dernière partie de soirée,",
// "notre invité exceptionnel,",
// "le baryton Sébastien Soules",
// "converti livreur à vélo par nécessité pendant le confinement lié à la maladie de covid-19",
// "viendra présenter sa nouvelle pièce d'opéra",
// "intitulée :",
// "aller chercher soi-même sa pizza en vélo quand on est valide et en bonne santé",
// "est une question de dignité humaine",
// "",
// "BIOGRAPHIES",
// "les interprètes sont né.e.s,",
// "les interprètes sont allé.e.s à l'école,",
// "les interprètes ont travaillé avec d'autres personnes.",
// "les interprètes sont de bonne humeur.",
// "comme il nous reste de la place dans la section 'biographies',",
// "les interprètes en profitent pour partager ce-dessous leur recette préférée de tarte à la tomate.",
// "",
// "CREDITS",
// "au moment de la création de cette pièce en 2022,",
// "lors de la précédente édition de La brèche festival,",
// "tous les partenaires privés et intitutionnels ont malheureusement décidé de retirer leur soutien au festival",
// "après avoir assisté à la première de ce concert performé.",
// "en conséquence de quoi, les interprètes vous signalent",
// "qu'aucun.e d'entre elleux ne sont rémunérés pour leur travail ce soir.",
// "en échange,",
// "nous vous proposons un protocole de paiement alternatif:",
// "entre chaque mouvement, nous nous interromprons pour tirer au sort dans la liste ci-dessous",
// "qui regroupe exhaustivement tous les problèmes personnels ou familiaux vécus par les interprètes",
// "pour lesquels iels pourraient recevoir un coup de main,",
// "et nous tirerons une personne au sort dans le public pour lui venir en aide.",
// "merci pour votre solidarité",
// "longue vie à la culture.",
// ""

// "cette soirée est rendue possible par nos généreux mécènes",
// "que nous tenons à remercier chaleureusement",
// "merci à Uber, Amazon, BNP Paribas et Uniqlo."
// chères spectatrices, chers spectateurs
// nous souhaitons vous informer qu'une coquille s'est manifestement glissé dans le programme de salle qui vous a été distribué ce soir
// nosu vous prions de bien vouloir nous excuser,
// c'est assez gênant.
// en fait, malgré ce qui a été écrit dans le feuillet que vous avez entre vos mains,
// nous tenons à *ne pas* remercier nos généreux mécènes
// parmi lesquels figurent un certain nombre de sociétés pratiquant publiquement et sans honte les pires formes d'exploitation possibles.
// afin de corriger cette erreur,
// l'orchestre va débuter la soirée par une création originale intitulée :
// 'morts au travail'
// composition dans laquelle un cri unique de une seconde sera interprété pour chaque personne employée par lesdites sociétés mécènes.
// Nous vous souhaitons une bonne soirée et vous prions une fois de plus de nous excuser pour cette erreur inexcusable.

// idée : personne n'est payé, le spectacle est gratuit, mais en échange les musiciens ont besoin d'un coup de main pour réparer des trucs chez elleux ou alors ils ont la flemme de faire à manger
// genre avant chaque morceau on commence pas tant qu'il y a pas une liste de personnes qui se sont portées volontaires pour aller faire à manger chez bob et bib.