export const data = [
    {player : 99, text :""},
    {player : 99, text :""},
    {player : 1, text : "   qu'est ce que tu lis ?"}, // il fume
    {player : 99, text : ""}, // elle lève la tête
    {player : 2, text : "c'est 'le Naufragé' de Thomas Bernhard"},
    {player : 2, text : "('the loser' en anglais)"},
    {player : 1, text : "    ça parle de quoi ?"},
    {player : 2, text : "hmm "},
    {player : 2, text : "ça parle de Glenn Gould "},
    {player : 2, text : "mais c'est une fiction hein"},
    {player : 2, text : "c'est raconté du point de vue de l'auteur"},
    {player : 2, text : "(qui n'était pas l'ami de Glenn Gould dans la vraie vie)"},
    {player : 1, text : "    ok"},
    {player : 2, text : "et en gros l'histoire c'est que l'auteur"},
    {player : 2, text : "donc Thomas Bernhard"},
    {player : 2, text : "et son ami"},
    {player : 2, text : "qui s'appelle 'Wertheimer'"},
    {player : 1, text : "    Wertheimer tu veux dire ?"}, // typo gothique sur le mot "WERTHEIMER"
    {player : 2, text : "oui bon voilà "},
    {player : 2, text : "hé ben ils rencontrent Glenn Gould dans leur école de piano à Salzburg"},
    {player : 2, text : "à Salzburg pardon"}, // re-blague typo gothique
    {player : 1, text : "    Qu'est ce que Glenn Gould fait en Autriche? il était pas canadien?"},
    {player : 2, text : "est ce que tu m'écoutes? c'est une FICTION j'ai dit"},
    {player : 1, text : "    ah ouioui "}, // puis fume
    {player : 2, text : "et là tu vois ils se baladent dans les couloirs du Mozartheum,"}, 
    {player : 1, text : "?"}, // typo gothique encore?
    {player : 2, text : "oui pardon c'est le nom de l'académie de musique"}, // typo gothique encore?
    {player : 2, text : "et donc, soudainement, à travers une porte entrebâillée"},
    {player : 2, text : "ils entendent jouer Glenn Gould."},
    {player : 2, text : "bon il s'agit des Variations Goldberg tu t'en doutes"},
    {player : 1, text : "   ...GoldBERG!"}, // en même temps, gro fayot
    {player : 2, text : "oui voilà bravo"},
    {player : 2, text : "et donc là ils reconnaissent le génie de Glenn Gould "},
    {player : 2, text : "et ça met instantanément fin"},
    {player : 2, text : "à leurs propres aspirations pianistiques."},
    {player : 2, text : "je cite : "},
    {player : 2, text : "'Le but de Wertheimer avait été'"}, // elle lit, peut être typo serif
    {player : 2, text : "'de devenir ce pianiste virtuose qui doit prouver sa maîtrise au monde musical,' "},
    {player : 2, text : "'d’année en année, jusqu’à ce qu’il tombe à la renverse,' "},
    {player : 2, text : "'s’agissant de Wertheimer, jusqu’à un âge fort avancé.' "},
    {player : 2, text : "'Glenn l’avait privé de ce but, pensai-je,' "},
    {player : 2, text : "'au moment où Glenn s’est assis et a joué les premières mesures des Variations Goldberg'"},
    {player : 2, text : "'Wertheimer avait dû l’entendre, pensai-je, il avait dû être anéanti par Glenn.'"},
    {player : 2, text : "fin de citation. "}, // elle arrête de lire, typo normale
    {player : 1, text : "   ...nan mais c'est clair, Glenn Gould c'était un génie"},
    {player : 1, text : "   ..."},
    {player : 1, text : "   mais"},
    {player : 2, text : "..."},
    {player : 2, text : "quoi 'mais'?"},
    {player : 1, text : "   c'est connu, il avait des troubles de la personnalité"},
    {player : 1, text : "   genre il a donné son dernier concert à 32 ans parce qu'il supportait plus le public"},
    {player : 1, text : "   écoute voir :"},
    {player : 1, text : "   'En 1962, il fait part à son entourage'"},
    {player : 1, text : "   'de sa fatigue de devoir se produire devant des auditoires distraits,'"},
    {player : 1, text : "   'qui toussent ou attendent la fausse note'"},
    {player : 1, text : "   ...nous dit wikipedia."},
    {player : 2, text : "oui ben c'est un option en effet"},
    {player : 2, text : "dès qu'on a l'occasion d'utiliser des termes pseudo-psychologiques"},
    {player : 2, text : "pour justifier notre propre médiocrité"},
    {player : 2, text : "et nous rassurer sur le fait qu'une autre personne plus conséquente que nous,"},
    {player : 2, text : "nous est en réalité inférieure "},
    {player : 2, text : "par la vertu d'un diagnostic amateur fait par dessus la jambe "},
    {player : 2, text : "on s'en prive pas."},
    {player : 99, text : ""},
    {player : 2, text : "tu devais pas arrêter de fumer en 2023 toi?"},
    {player : 1, text : "    ... "},
    {player : 1, text : "    allez, tu sais quoi"},
    {player : 1, text : "    c'était ma dernière cigarette."},
    {player : 1, text : "    comme ça je tousserai plus aux concerts "},
    {player : 1, text : "    et Glenn Gould sera fier de moi."}
]